"""RSS 对话框 C：设置对话框（前半）。"""

import logging
import re

from core.qt_bootstrap import import_qt

_, QtCore, QtGui, QtWidgets = import_qt()

from .dialogs_e import _CategoryDialog, _FilterRuleDialog, _KeywordDialog
from .styles import _btn_primary_style, _btn_style
from .utils import _bind_geometry

logger = logging.getLogger("rss_aggregator")

class _SettingsDialog(QtWidgets.QDialog):
    def __init__(self, owner, parent=None):
        super().__init__(parent)
        self.setWindowTitle("RSS 设置")
        self.setMinimumSize(500, 600)
        _bind_geometry(self, "rss_settings", default_size=(500, 600))
        self.owner = owner
        self._apply_dialog_theme()

        scroll = QtWidgets.QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.viewport().setAutoFillBackground(False)
        scroll.setStyleSheet("QScrollArea { background: transparent; border: none; }")
        content = QtWidgets.QWidget()
        content.setAutoFillBackground(False)
        content.setObjectName("rssSettingsContent")
        content.setStyleSheet("QWidget#rssSettingsContent { background: transparent; }")
        lay = QtWidgets.QVBoxLayout(content)
        lay.setContentsMargins(16, 16, 16, 16)
        lay.setSpacing(12)

        settings_group = QtWidgets.QGroupBox("代理设置")
        settings_lay = QtWidgets.QFormLayout(settings_group)
        self.in_proxy = QtWidgets.QLineEdit()
        self.in_proxy.setPlaceholderText("http://127.0.0.1:7890 或 socks5://127.0.0.1:1080")
        self.in_proxy.setText(self.owner.context.config.get("rss.proxy", ""))
        settings_lay.addRow("代理地址", self.in_proxy)
        lay.addWidget(settings_group)

        cleanup_group = QtWidgets.QGroupBox("数据清理")
        cleanup_lay = QtWidgets.QHBoxLayout(cleanup_group)
        cleanup_lay.addWidget(QtWidgets.QLabel("清理"))
        self.spin_cleanup_days = QtWidgets.QSpinBox()
        self.spin_cleanup_days.setRange(7, 365)
        self.spin_cleanup_days.setValue(self.owner.context.config.get("rss.cleanup_days", 30))
        self.spin_cleanup_days.setSuffix(" 天前的数据")
        cleanup_lay.addWidget(self.spin_cleanup_days)
        btn_cleanup = QtWidgets.QPushButton("清理")
        btn_cleanup.setStyleSheet(_btn_primary_style())
        btn_cleanup.clicked.connect(self._cleanup_old)
        cleanup_lay.addWidget(btn_cleanup)
        lay.addWidget(cleanup_group)

        notify_group = QtWidgets.QGroupBox("通知设置")
        notify_lay = QtWidgets.QFormLayout(notify_group)
        self.chk_notify = QtWidgets.QCheckBox("启用桌面通知")
        self.chk_notify.setChecked(self.owner.context.config.get("rss.notification_enabled", True))
        self.chk_notify.stateChanged.connect(lambda s: self.owner.context.config.set("rss.notification_enabled", s == QtCore.Qt.CheckState.Checked.value))
        notify_lay.addRow(self.chk_notify)
        lay.addWidget(notify_group)

        categories_group = QtWidgets.QGroupBox("分类管理")
        categories_lay = QtWidgets.QVBoxLayout(categories_group)
        self.category_list = QtWidgets.QListWidget()
        self.category_list.setMaximumHeight(100)
        categories_lay.addWidget(self.category_list)
        cat_btn_row = QtWidgets.QHBoxLayout()
        btn_add_cat = QtWidgets.QPushButton("添加分类")
        btn_add_cat.setStyleSheet(_btn_style())
        btn_add_cat.clicked.connect(self._show_category_dialog)
        btn_edit_cat = QtWidgets.QPushButton("编辑")
        btn_edit_cat.setStyleSheet(_btn_style())
        btn_edit_cat.clicked.connect(self._edit_category)
        btn_del_cat = QtWidgets.QPushButton("删除")
        btn_del_cat.setStyleSheet(_btn_style())
        btn_del_cat.clicked.connect(self._remove_category)
        cat_btn_row.addWidget(btn_add_cat)
        cat_btn_row.addWidget(btn_edit_cat)
        cat_btn_row.addWidget(btn_del_cat)
        cat_btn_row.addStretch(1)
        categories_lay.addLayout(cat_btn_row)
        lay.addWidget(categories_group)

        keywords_group = QtWidgets.QGroupBox("关键词提醒")
        keywords_lay = QtWidgets.QVBoxLayout(keywords_group)
        self.keyword_list = QtWidgets.QListWidget()
        self.keyword_list.setMaximumHeight(100)
        keywords_lay.addWidget(self.keyword_list)
        kw_btn_row = QtWidgets.QHBoxLayout()
        btn_add_kw = QtWidgets.QPushButton("添加关键词")
        btn_add_kw.setStyleSheet(_btn_style())
        btn_add_kw.clicked.connect(self._show_keyword_dialog)
        btn_del_kw = QtWidgets.QPushButton("删除选中")
        btn_del_kw.setStyleSheet(_btn_style())
        btn_del_kw.clicked.connect(self._remove_keyword)
        kw_btn_row.addWidget(btn_add_kw)
        kw_btn_row.addWidget(btn_del_kw)
        kw_btn_row.addStretch(1)
        keywords_lay.addLayout(kw_btn_row)
        lay.addWidget(keywords_group)

        rules_group = QtWidgets.QGroupBox("过滤规则")
        rules_lay = QtWidgets.QVBoxLayout(rules_group)
        self.rule_list = QtWidgets.QListWidget()
        self.rule_list.setMaximumHeight(100)
        rules_lay.addWidget(self.rule_list)
        rule_btn_row = QtWidgets.QHBoxLayout()
        btn_add_rule = QtWidgets.QPushButton("添加规则")
        btn_add_rule.setStyleSheet(_btn_style())
        btn_add_rule.clicked.connect(self._show_filter_dialog)
        btn_del_rule = QtWidgets.QPushButton("删除选中")
        btn_del_rule.setStyleSheet(_btn_style())
        btn_del_rule.clicked.connect(self._remove_rule)
        btn_toggle_rule = QtWidgets.QPushButton("启用/禁用")
        btn_toggle_rule.setStyleSheet(_btn_style())
        btn_toggle_rule.clicked.connect(self._toggle_rule)
        rule_btn_row.addWidget(btn_add_rule)
        rule_btn_row.addWidget(btn_del_rule)
        rule_btn_row.addWidget(btn_toggle_rule)
        rule_btn_row.addStretch(1)
        rules_lay.addLayout(rule_btn_row)
        lay.addWidget(rules_group)

        history_group = QtWidgets.QGroupBox("阅读历史")
        history_lay = QtWidgets.QVBoxLayout(history_group)
        self.history_list = QtWidgets.QListWidget()
        self.history_list.setMaximumHeight(120)
        history_lay.addWidget(self.history_list)
        btn_refresh_history = QtWidgets.QPushButton("刷新历史")
        btn_refresh_history.setStyleSheet(_btn_style())
        btn_refresh_history.clicked.connect(self._load_history)
        history_lay.addWidget(btn_refresh_history)
        lay.addWidget(history_group)

        stats_group = QtWidgets.QGroupBox("统计信息")
        stats_lay = QtWidgets.QVBoxLayout(stats_group)
        self.lb_stats = QtWidgets.QLabel("")
        stats_lay.addWidget(self.lb_stats)
        btn_refresh_stats = QtWidgets.QPushButton("刷新统计")
        btn_refresh_stats.setStyleSheet(_btn_style())
        btn_refresh_stats.clicked.connect(self._load_stats)
        stats_lay.addWidget(btn_refresh_stats)
        lay.addWidget(stats_group)

        lay.addStretch(1)
        scroll.setWidget(content)
        main_lay = QtWidgets.QVBoxLayout(self)
        main_lay.addWidget(scroll)

        btn_row = QtWidgets.QHBoxLayout()
        btn_row.addStretch(1)
        btn_save = QtWidgets.QPushButton("保存设置")
        btn_save.setStyleSheet(_btn_primary_style())
        btn_save.clicked.connect(self._save_settings)
        btn_close = QtWidgets.QPushButton("关闭")
        btn_close.setStyleSheet(_btn_style())
        btn_close.clicked.connect(self.accept)
        btn_row.addWidget(btn_close)
        btn_row.addWidget(btn_save)
        main_lay.addLayout(btn_row)

        self._load_keywords()
        self._load_rules()
        self._load_stats()
        self._load_categories()
        self._load_history()
